kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: docker-build
  namespace: shall-workspace
  labels:
    name: docker-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'origin-ruby-sample:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'ruby:latest'
      env:
        - name: EXAMPLE
          value: sample-app
  postCommit:
    args:
      - bundle
      - exec
      - rake
      - test
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ruby-hello-world.git'
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial